### ISSUE TITLE
error in DCOS katana with manual VGA 093 install instructions

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-dcos#1]
When applying the manual VGA installation instructions for 093 (https://github.com/magneticio/vamp.io/blob/v093/content/documentation/installation/v0.9.3/dcos.md) the following error appears in the VGA container:

```
/sbin/runsvdir started
./run: line 21: VAMP_KEY_VALUE_STORE_PATH: not provided.
./run: line 21: VAMP_KEY_VALUE_STORE_PATH: not provided.
./run: line 21: VAMP_KEY_VALUE_STORE_PATH: not provided.
```

**Comment by iamtew** [comment]
Documentation updated under https://github.com/magneticio/vamp.io/commit/b4ce246c6187c02e7077021712df1334d689e5b9
